files_to_sync:
  - src: .distro/
    dest: ./
    delete: true
    filters:
      - "protect .git*"
      - "protect sources"
      - "protect changelog"
      - "- plans/rpminspect.fmf"
      - "- plans/rpmlint.fmf"
  - .packit.yaml

specfile_path: .distro/cmake-template.spec
upstream_package_name: CMake-Template
downstream_package_name: cmake-template
upstream_tag_template: v{version}

targets: &targets
  - fedora-all-x86_64
  - fedora-all-aarch64
  - epel-10-x86_64
  - epel-10-aarch64
  - epel-9-x86_64
  - epel-9-aarch64

jobs:
  - &copr_build
    job: copr_build
    trigger: pull_request
  - &tests
    job: tests
    trigger: pull_request
    fmf_path: .distro
  - <<: *copr_build
    trigger: commit
    branch: main
    project: nightly
  - <<: *tests
    trigger: commit
    branch: main
  - <<: *copr_build
    trigger: release
    owner: lecris
    project: release
  - <<: *tests
    trigger: release
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
