repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/Takishima/cmake-pre-commit-hooks
    rev: v1.5.3
    hooks:
      - id: clang-format
        args:
          - '-Bcmake-build-pre-commit'
          - '-i'
      - id: clang-tidy
        args:
          - '-Bcmake-build-pre-commit'
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
        # Disable because of sphinx compatibility
        stages: [ manual ]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-github-workflows
