name: CI
run-name: >
  CI (${{ github.event_name }})
  ${{ github.event_name == 'pull_request' && format('PR#{0}', github.event.number) || '' }}

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: ./.github/workflows/step_pre-commit.yaml

  tests:
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_test.yaml

  docs:
    name: 📘 docs
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_docs.yaml

  coverage:
    name: 👀 coverage
    needs: [ tests ]
    uses: ./.github/workflows/step_coverage.yaml

  static-analysis:
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_static-analysis.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  pass:
    name: ✅ Pass
    needs: [ pre-commit, tests, coverage, docs, static-analysis ]
    runs-on: ubuntu-latest
    steps:
      - name: Check all CI jobs
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
    if: always()
