name: 🚀 release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  # Run common tests that can change in time
  pre-commit:
    uses: ./.github/workflows/step_pre-commit.yaml

  tests:
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_test.yaml
    with:
      mask-experimental: true

  # Normally this is unnecessary, but for sonarcloud, this tags the new version
  static-analysis:
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_static-analysis.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docs:
    name: 📘 docs
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_docs.yaml

  tests-pass:
    name: ✅ Pass
    needs: [ pre-commit, tests, static-analysis, docs ]
    runs-on: ubuntu-latest
    steps:
      - name: Check all CI jobs
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
    if: always()

  release:
    needs: [ tests-pass ]
    name: 🚀 Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v1
        with:
          name: Template ${{ github.ref_name }}
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') }}
          generate_release_notes: true
