name: static-analysis

on:
  workflow_call:
    secrets:
      QODANA_TOKEN:
        required: true

jobs:
  qodana:
    name: Qodana
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
